field: 95f98672-9562-44a0-8639-92d2b55ceeb6 # Body Content
fieldLayouts:
  b96ba22c-1dc3-4984-9618-dba5bf9072e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: abb455ba-032b-461d-9c8d-dca9ed3fc7bd # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53b039bc-1e34-432c-adfd-6ebaa5e40260
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4b9eed77-fa62-4ecc-9486-744a64f075d4 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7f50fae-c8f1-4a55-9231-3186509b9f19
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 8ed4044d-89b6-4d6b-a8a3-e303f533263a # Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc2dbe43-5774-4787-a8a6-a78db3a25d39
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 76e79da0-ac5e-42ef-b095-ff42e4ff2b28
        userCondition: null
fields:
  4b9eed77-fa62-4ecc-9486-744a64f075d4: # Caption
    columnSuffix: xngnntxq
    contentColumnType: string(250)
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: true
    settings:
      byteLimit: 250
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  8ed4044d-89b6-4d6b-a8a3-e303f533263a: # Style
    columnSuffix: uoxadpzo
    contentColumnType: string
    fieldGroup: null
    handle: style
    instructions: null
    name: Style
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Wide
            -
              - value
              - wide
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
  abb455ba-032b-461d-9c8d-dca9ed3fc7bd: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'At least 768px wide. For best result, use 1000px min. if the wide style is used.'
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:c9a4fbad-6ca0-4e20-ba72-da2c14a38190' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: thumbs
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c9a4fbad-6ca0-4e20-ba72-da2c14a38190' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\assets\WidthConditionRule
                  -
                    - uid
                    - 73c6baec-2203-47fa-bee7-633be75c6120
                  -
                    - operator
                    - '>='
                  -
                    - value
                    - '768'
                  -
                    - maxValue
                    - ''
      selectionLabel: 'Select an image'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:c9a4fbad-6ca0-4e20-ba72-da2c14a38190' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 3
