fieldLayouts:
  a9d58556-baca-4c30-916a-bef0d1ee1f14:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: be381213-38ff-4fec-a714-0d5578979925
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a73e7c96-e9d2-4751-bf01-8a6baf5f3c46 # Alt Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64372242-c3cf-4a77-b3b3-90704f40d841
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 560e7c36-f763-440f-b9b5-1d87228bc6df # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 230731e5-bcd8-4470-b580-6f1577e6f6fc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c1e3a4d5-1e1c-4d1a-990f-39e3b823150c
        userCondition: null
fs: imagesFs
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: language
transformFs: internalFs
transformSubpath: images
