columnSuffix: okpymjyq
contentColumnType: string(255)
fieldGroup: 761cddc2-d969-4560-b5de-4bf2a393cb8a # Common
handle: subheading
instructions: null
name: Subheading
searchable: false
settings:
  byteLimit: 255
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
