#!/bin/bash

if [ -z $1 ]
then
    echo Project name missing
    exit 1
fi

echo Installing project $1...

ddev config --project-name=$1
ddev start &&
ddev composer install --no-dev &&
ddev craft install --interactive=0 --username=admin --password=password --email=admin@example.com &&
ddev craft migrate/up --interactive=0 &&
ddev npm install &&
ddev describe &&
ddev launch



