defaultPlacement: end
enableVersioning: true
handle: post
name: Post
propagationMethod: all
siteSettings:
  2393c71c-94e8-4e90-bb19-949696b8be0b: # English
    enabledByDefault: true
    hasUrls: true
    template: _sections/post
    uriFormat: 'posts/{slug}'
  b7acd2cf-9449-4637-a40c-2e266a19cc19: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _sections/post
    uriFormat: 'beitraege/{slug}'
type: channel
